### ISSUE TITLE
Byte needs to improve his icon

### ISSUE THREAD

**Issue by alainm23** [alainm23/byte#1]
The design of Byte is inspired by a model created by Harvey Cabaguio 
https://plus.google.com/photos/photo/108415810545254910289/6451962053631187698

Thank you very much in advance if you can help me with this problem

**Comment by alainm23** [comment]
![image](https://user-images.githubusercontent.com/33765137/59367634-22836c00-8d02-11e9-97b9-356a4b627f21.png)
the current icon looks good, but with a very flat style and can still be improved

**Comment by trst** [comment]
It might help to add a radial gradient to the background colour (e.g., current red/pink to a darker hue) and potentially some internal highlights to the symbol (i.e., a 1-2px internal shadow in 255,255,255). Might be just enough depth to make the icon pop in the dock

**Comment by alainm23** [comment]
That sounds incredible, but the truth is I'm not very good at designing and I do not have the slightest idea how to make a gradient

**Comment by trst** [comment]
Do you have access to the icon’s source files? Like an Inkscape SVG or something that I can take a look at?

**Comment by alainm23** [comment]
Yes, here: https://github.com/alainm23/byte/blob/master/data/icons/128/com.github.alainm23.byte.svg

**Comment by Fatih20** [comment]
I think this can be improved to be compliant with the [eOS HIG](https://elementary.io/docs/human-interface-guidelines#color) while also being more unique (than other music player) and aesthetically pleasing. I'll get on it. I think the icon I would be designing won't have a base shape, It would be like audacity icon. A headphone with a cable and sound wave. What do you think? In the meantime, I could make the current icon more compliant.

**Comment by Fatih20** [comment]
> I'm not very good at designing

The icon of planner looks pretty epic, so I don't know what you're talking about.

**Comment by alainm23** [comment]
@Fatih20 Thank you for the compliment but the Planner icon was designed by **alecaddd**

**Comment by DanyGee** [comment]
My view on the case :wink: 
![Byte_Vinyl_Test-01](https://user-images.githubusercontent.com/26818551/62714466-eec17b80-b9fe-11e9-91eb-da7b681f7e0c.png)
![Screenshot from 2019-08-08 17 03 59@2x](https://user-images.githubusercontent.com/26818551/62714492-00a31e80-b9ff-11e9-9fbd-995dda6b67e3.png)
![Screenshot from 2019-08-08 17 04 30@2x](https://user-images.githubusercontent.com/26818551/62714493-00a31e80-b9ff-11e9-8758-3c20b65843d1.png)
![Screenshot from 2019-08-08 17 04 44@2x](https://user-images.githubusercontent.com/26818551/62714494-00a31e80-b9ff-11e9-8805-a70e3b301628.png)

**Comment by Fatih20** [comment]
That is cool. But the eOS HIG stated for us to avoid giving text to icons. Even more so in this case where the text is barely readable. That is just going to be a pixelated mess when you make the 16 pizel size icon. Which is necessary as stated in the eOS HIG.

**Comment by DanyGee** [comment]
> That is cool. But the eOS HIG stated for us to avoid giving text to icons. Even more so in this case where the text is barely readable. That is just going to be a pixelated mess when you make the 16 pizel size icon. Which is necessary as stated in the eOS HIG.

You're right. I'll leave it then as an possible inspiration :wink:

**Comment by Fatih20** [comment]
Where did you get that vinyl image? Give me the SVG if you have it, I'll see what I can do.

**Comment by DanyGee** [comment]
> Where did you get that vinyl image? Give me the SVG if you have it, I'll see what I can do.

I edited it in Adobe Illustrator. Saving as SVG there brakes it.
I'll try to recreate it from scratch in Inkscape as SVG, following the eOS HIG - you can try it too. Just use the image here as a reference.

**Comment by alainm23** [comment]
Hi guys, thanks for your comments and your desire to improve this application. In my opinion Byte should keep the design of the current icon but improving it maybe with a little bit of gradient and making it more compatible with elementary OS HIG.

**Comment by Fatih20** [comment]
But why? If so, then it's just an itunes logo with a different color. It doesn't show the app's uniqueness despite it being unique.

**Comment by Fatih20** [comment]
When you made this app, I'm damn sure you didn't just rip another app and then only rebranding it to make it looks different. Same thing with icon. You shouldn't be complacent in dping this stuff. Certainly, you shouldn't just copy someone else's icon (in this case, apple). Spotify icon has NOTHING in its icon to imply it's a music player. Because they're emphasizing "Spotify" instead of the apps functionality as a music player.

**Comment by alainm23** [comment]
Hey guys what do you thinks?

![image](https://user-images.githubusercontent.com/33765137/62793228-ae154100-ba96-11e9-9f6f-f4651c1acfe4.png)

**Comment by DanyGee** [comment]
Made the icon more eOS HIG compliant...
![byte_note_icon](https://user-images.githubusercontent.com/26818551/62795228-952c8000-bad6-11e9-9d03-2a61c6d78a85.png)
![Screenshot from 2019-08-09 18 52 02@2x](https://user-images.githubusercontent.com/26818551/62795369-db81df00-bad6-11e9-8967-ea5fb2d92284.png)

![byte_play_icon](https://user-images.githubusercontent.com/26818551/62795240-9bbaf780-bad6-11e9-9255-3a73804dd6ac.png)
![Screenshot from 2019-08-09 18 51 33@2x](https://user-images.githubusercontent.com/26818551/62795375-e0df2980-bad6-11e9-851f-ff99e60e8923.png)

**Comment by alainm23** [comment]
What if we add a sound wave instead of the music icon. Obviously maintaining the current color.

![image](https://user-images.githubusercontent.com/33765137/62796358-aa85b800-ba9e-11e9-9e9e-c9d5b9ebdb7f.png)

**Comment by DanyGee** [comment]
![byte_soundwave2 svg](https://user-images.githubusercontent.com/26818551/62805435-455ab280-baf0-11e9-994f-e6fec2abc490.png)
![Screenshot from 2019-08-09 21 51 28@2x](https://user-images.githubusercontent.com/26818551/62805460-586d8280-baf0-11e9-81d2-d15346b2ef1c.png)

![byte_soundwave svg](https://user-images.githubusercontent.com/26818551/62805441-4c81c080-baf0-11e9-8644-27e824ec4195.png)
![Screenshot from 2019-08-09 21 49 53@2x](https://user-images.githubusercontent.com/26818551/62805465-5f949080-baf0-11e9-81c2-70e131e7c97f.png)

**Comment by Fatih20** [comment]
Did you follow the guideline?

The gradient is too sharp. It should be more subtle.
It's too cramped. Would be hard to make smaller sizes. 

The wave on the second one is already used by an elementary app used to monitor system component. So, I thnk we shouldn't use that.

**Comment by DanyGee** [comment]
> Did you follow the guideline?
> 
> The gradient is too sharp. It should be more subtle.
> It's too cramped. Would be hard to make smaller sizes.
> 
> The wave on the second one is already used by an elementary app used to monitor system component. So, I thnk we shouldn't use that.

I see u are theoretically well prepared.
Now I really want to see your perfect icon for this app :eyes:

**Comment by Fatih20** [comment]
I have made the pull request. Check it out.

**Comment by DanyGee** [comment]
> I have made the pull request. Check it out.

How to actually see the redesign?

**Comment by DanyGee** [comment]
OK...you are definately a better commenter than a creator.
If that is what you call "following the eOS HIG" then I have no other questions :face_with_head_bandage: 
![download (2) svg](https://user-images.githubusercontent.com/26818551/62819081-6a7f0d80-bb50-11e9-8512-9c8e6657f077.png)
![download (1) svg](https://user-images.githubusercontent.com/26818551/62819082-6a7f0d80-bb50-11e9-839b-30f7cfd8c097.png)
![download svg](https://user-images.githubusercontent.com/26818551/62819083-6b17a400-bb50-11e9-88ba-1f2f14559dfb.png)

**Comment by Fatih20** [comment]
The upper 2 is an experiment, so I have not made them compliant with the HIG. The design with the vinyl followed the HIG. Which part of it it didn't comply with?

**Comment by DanyGee** [comment]
Commenting, experimenting is easy - cause it requires almost no effort.
The 3rd design is just plain ugly - it will fit more to Papirus Icon set than to more "skeuomorphic" nature of eOS icon set.

**Comment by Fatih20** [comment]
The third design comply by the HIG on the first point. **Avoid slapping a shape to an unnecessary base shape** and I think we should go from there when designing this icon because it's easy to slap a musical keynote  to a base shape. But not much originality there.

We should look at spotify icons, it's different than the icon of most musical player but somehow it can convey its uses. 

You can say that the third icon is bad or not skeuomorphic (of which I doubt, because I have followed the steps necessary to look it skeuomorphic according to the HIG). Can you make it skeuomorphic? It was you who suggest the vinyl design. That's where I got the suggestion.

**Comment by DanyGee** [comment]
OK, then make it more skeuomorphic, cause now its just almost flat.
And here some details of an icon from eOS...
Let's pay attention to those tiny details...
![Screenshot from 2019-08-10 10 02 54@2x](https://user-images.githubusercontent.com/26818551/62819506-6ce46600-bb56-11e9-919d-452e63b024f8.png)

And here my latest attempt just for comparison...
I can see it lacks some finer details on the shadow and outer edge, but I'm getting there...
![Screenshot from 2019-08-10 10 03 59@2x](https://user-images.githubusercontent.com/26818551/62819518-9e5d3180-bb56-11e9-923c-daa1126971ca.png)
Now actually, the background is the least of the problems. The actual pictogram is the problem.
How else could we pack "music","player" and "byte" into one image? :thinking:

**Comment by Fatih20** [comment]
That's the idea of the vinyl, because it can be bitten off unlike base shape. And it can convey music music and player at the same time.

**Comment by DanyGee** [comment]
That's why I like it the most for now and that's what first crossed my mind...
I'll design the vinyl once more.
Meanwhile...
Something like this could also be interesting...
It's beats...
B for byte...
Shape resembling a music note...
![images](https://user-images.githubusercontent.com/26818551/62819672-6a830b80-bb58-11e9-9105-a81faff52d81.png)

**Comment by Fatih20** [comment]
We can. Should we use negative space or colored?

**Comment by DanyGee** [comment]
Lets aim for a final product while presenting an icon.
Just create it as if it was going to production.
Lets go with color.

**Comment by DanyGee** [comment]
OK, this is what I came up with today.
![Vinyl_record (copy) svg](https://user-images.githubusercontent.com/26818551/62825621-4d2d5c00-bbaf-11e9-8a49-d8ec593b4b47.png)
![Screenshot from 2019-08-10 20 40 18@2x](https://user-images.githubusercontent.com/26818551/62825626-5a4a4b00-bbaf-11e9-9f58-ee01016b98c7.png)
![Screenshot from 2019-08-10 20 40 44@2x](https://user-images.githubusercontent.com/26818551/62825628-5dddd200-bbaf-11e9-88c1-4ab3c7d0df44.png)
![Screenshot from 2019-08-10 20 41 08@2x](https://user-images.githubusercontent.com/26818551/62825629-61715900-bbaf-11e9-8659-ed3df16840bf.png)

**Comment by Fatih20** [comment]
I think the small dot in the middle is pointless. At smaller size it won't be visible.

**Comment by DanyGee** [comment]
> I think the small dot in the middle is pointless. At smaller size it won't be visible.

Didn't decide whether to delete it or not yet :thinking: 
Majority of little touches will not be visible in smaller sizes, but its still nice to include them, when visible.

**Comment by Fatih20** [comment]
I think you should get rid of it when designing the icon with size 32 pixel and below.

**Comment by DanyGee** [comment]
And another variation, but I think it is practically a beats rip-off.
![byte_vinyl_beats_white svg](https://user-images.githubusercontent.com/26818551/62833186-e190d080-bc3a-11e9-9f92-0111f77966d9.png)
![Screenshot from 2019-08-11 13 18 29@2x](https://user-images.githubusercontent.com/26818551/62833187-eeadbf80-bc3a-11e9-8d5a-97f294af3f35.png)
![Screenshot from 2019-08-11 13 18 44@2x](https://user-images.githubusercontent.com/26818551/62833188-ef465600-bc3a-11e9-8923-ebcc95cebcaa.png)
![Screenshot from 2019-08-11 13 18 57@2x](https://user-images.githubusercontent.com/26818551/62833189-ef465600-bc3a-11e9-8efc-b0081604f01c.png)

**Comment by DanyGee** [comment]
And another variation, but It looks practically like beats™ rip-off :eyes: 
![byte_vinyl_beats_white svg](https://user-images.githubusercontent.com/26818551/62833232-a773fe80-bc3b-11e9-8d31-61cf4795e472.png)

![Screenshot from 2019-08-11 13 25 37@2x](https://user-images.githubusercontent.com/26818551/62833224-9dea9680-bc3b-11e9-9765-8156a34c3441.png)
![Screenshot from 2019-08-11 13 25 47@2x](https://user-images.githubusercontent.com/26818551/62833225-9e832d00-bc3b-11e9-8d0b-76093e6f9422.png)
![Screenshot from 2019-08-11 13 26 08@2x](https://user-images.githubusercontent.com/26818551/62833226-9e832d00-bc3b-11e9-8109-8d9c3d08ac9e.png)

**Comment by Fatih20** [comment]
I think the first one is better because the "byte" meaning is more obvious. People will connotate the second one with "beats" instead of "byte"

Also, have you added the extruded or inset effect for the pictogram?

**Comment by DanyGee** [comment]
> Also, have you added the extruded or inset effect for the pictogram?

No, I didn't.

**Comment by DanyGee** [comment]
Added a bit of light to bite finish...
![byte_vinyl (another copy) svg](https://user-images.githubusercontent.com/26818551/62855871-a30b1c80-bcf3-11e9-9d82-dadea19af45f.png)

**Comment by Fatih20** [comment]
Should the bitten part have the black outline too or not? What do you think?

**Comment by DanyGee** [comment]
Here we go...
Which one feels better?
![byte_vinyl svg](https://user-images.githubusercontent.com/26818551/62862456-23d31400-bd06-11e9-906d-f32f2aa57de8.png)
![byte_vinyl svg2](https://user-images.githubusercontent.com/26818551/62862457-246baa80-bd06-11e9-8ff1-832fb43e9739.png)

**Comment by Fatih20** [comment]
I feel like the first one without the outline is better because the bite look more authentic, the second one looks like the bite is "staged" if you know what I mean.

**Comment by alainm23** [comment]
First of all, I have to thank everyone for their ideas and their time.

I've been thinking about how to improve the Byte icon and this is my design (something basic)

- Basically, the same icon, just without the edge and adding some curved lines to the sides (since Byte is not just a music player, it is also an online radio player)

![image](https://user-images.githubusercontent.com/33765137/71781302-ffb8ed80-2f9a-11ea-9573-8ba7a0fdbdef.png)

**Comment by Fatih20** [comment]
Dude no, the musical note symbol would be unrecognizable on low ppi monitor. @alainm23

**Comment by alainm23** [comment]
Or maybe something more generic.

![image](https://user-images.githubusercontent.com/33765137/71781581-67246c80-2f9e-11ea-839b-3f876fd7cec9.png)

**Comment by Fatih20** [comment]
Can you upload the svg? I'll improve it so that it complies by the guideline.

**Comment by alainm23** [comment]
Great, I'm very grateful to you.

[com.github.alainm23.byte.svg.zip](https://github.com/alainm23/byte/files/4023497/com.github.alainm23.byte.svg.zip)

**Comment by Fatih20** [comment]
Cool. I'll make a commit.
