### ISSUE TITLE
Crash during import: Error creating thread

### ISSUE THREAD

**Issue by okin** [alainm23/byte#23]
byte crashed for me today when importing during startup with the following message:

```
(com.github.alainm23.byte:4112): GLib-ERROR **: 19:37:29.322: creating thread 'found_local_music_file': Error creating thread: Die Ressource ist zur Zeit nicht verfügbar
[1]    4112 trace trap  com.github.alainm23.byte
```

_Die Ressource ist zur Zeit nicht verfügbar_ translates to~ _the resource is currently unavailable_.
The error isn't currently reproducable. Anyhow I think such a case could be handled a little bit more gracefully.

**Comment by alainm23** [comment]
It seems to be the same error as #17
