### ISSUE TITLE
Byte does not respect my Window Control Layout 

### ISSUE THREAD

**Issue by wilsenhc** [alainm23/byte#24]
I have setup my Window Control Layout using elementary Tweaks, and when using Byte it doesn't respect that setting

![Screenshot from 2019-08-15 18 21 01](https://user-images.githubusercontent.com/13445515/63130822-c222dc00-bf89-11e9-812f-44ae0435cad5.png)

**Comment by alainm23** [comment]
Thanks for your comments, I don't think this is a mistake. Byte has a specific type of design that makes it incompatible with custom window control. I'm sorry I can't help you.
