### ISSUE TITLE
Album covers are not imported correctly

### ISSUE THREAD

**Issue by DanyGee** [alainm23/byte#25]
Some covers fail to properly import and show in library.
Trying a couple of resets and imports of the same amount of mp3's showed that different covers fail at different imports.

**Comment by alainm23** [comment]
I have been working on this problem this week and I think it has been fixed. Soon a new update.

**Comment by DanyGee** [comment]
Version **0.1.3** compiled locally - all album covers loading correctly :heavy_check_mark: 
On first import all album covers are drawn a little bit smaller...
![Screenshot from 2019-08-20 09 29 30@2x](https://user-images.githubusercontent.com/26818551/63328496-90ff2e80-c330-11e9-9bdc-94fc68b99e7d.png)
Once I quit and relaunch Byte, all covers get their standard size back...
![Screenshot from 2019-08-20 09 29 46@2x](https://user-images.githubusercontent.com/26818551/63328549-a411fe80-c330-11e9-8f7c-549b3a9fa980.png)

**Comment by DanyGee** [comment]
Looks like the bug is related to HiDPi scaling.
On 1920x1080 resolution new covers are displayed correctly.
On 3840x2160 resolution all whats newly added for first time gets smaller covers.
After program restart, covers get normal.
Basically byte needs additional restart after something new is added to correct wrong cover size.
