### ISSUE TITLE
Cannot delete radio station while it's being played

### ISSUE THREAD

**Issue by DanyGee** [alainm23/byte#26]
byte v0.1.3
Trying to delete a radio station while it being played result in a nasty hang of the program with delete confirmation dialog not reacting to either **cancel** or **delete** - had to kill the byte process to exit this.

**Comment by alainm23** [comment]
Thank you very much for commenting, I am trying to reproduce the error but I did not get it.

![byte-radio-delete](https://user-images.githubusercontent.com/33765137/63524398-950e8600-c4c1-11e9-879b-09eb106f77d8.gif)

**Comment by DanyGee** [comment]
Try these steps:
1. Play a radio
2. Quit byte while playing a radio (radio still plays after quit on my machine)
3. Go to radios and try to delete the playing radio

What is the outcome now?

**Comment by alainm23** [comment]
This is very strange, could you run Byte from the terminal and tell me if you send an error?

![byte-radio-delete2](https://user-images.githubusercontent.com/33765137/63534384-ac0aa380-c4d4-11e9-9061-94b68202b833.gif)

**Comment by DanyGee** [comment]
Now when I tried it radio stops playing after I quit the app both from launcher and terminal, and in both cases I can delete playing radio without hanging. This is very strange :thinking: 
Terminal output was like this (first launch, play radio, quit = radio stopped playing) :heavy_check_mark: 
(Second launch, play radio, delete radio = radio deleted, but still playing, but stopped after app quit) :heavy_check_mark: 
![Screenshot from 2019-08-22 19 12 36@2x](https://user-images.githubusercontent.com/26818551/63535223-3b35ac80-c511-11e9-9a88-b1fcc02b1a21.png)

**Comment by alainm23** [comment]
What's up friend. Some update with this problem, still giving you the same error.

**Comment by DanyGee** [comment]
No, so far, so good.
Lets close the error.
