### ISSUE TITLE
The backward_button, playback_button, forward_button should be insensitive in the Welcome view

### ISSUE THREAD

**Issue by ryonakano** [alainm23/byte#3]
Thank you for creating such a cute app!

![screenshot from 2019-01-19 19-21-30](https://user-images.githubusercontent.com/26003928/51425450-ad62ad80-1c1f-11e9-8f18-8c31e1607696.png)

I think in the Welcome view the backward_button, playback_button, forward_button should be insensitive like the screenshot above, because in that view users can't play anything yet.

**Comment by alainm23** [comment]
You are right.
