### ISSUE TITLE
Help to publish on Flathub

### ISSUE THREAD

**Issue by PizzaLovingNerd** [alainm23/byte#4]
Can we get a Flatpak for byte so we can get it on other, non-elementary distros?

**Comment by alainm23** [comment]
Thank for asking.
I will do my best to post Byte on Flathub.

**Comment by alainm23** [comment]
Try to publish Planner in Flathub but don't get more than creating a flatpack package. If someone could help me with this problem, I would be very grateful.

**Comment by PizzaLovingNerd** [comment]
Try this:
https://github.com/flathub/flathub/wiki/App-Submission

Basically you fork the Flathub repo, then a branch with your app name, add your app, and create a pull request.
