### ISSUE TITLE
Unable to play album after "opening" an artist

### ISSUE THREAD

**Issue by Roelofpieter** [alainm23/byte#52]
Hello there. I am not sure weather this is a bug or a missing feature (or an error on my side) . When (in Byte) going to Artist, and then "open" a specific artist, on the bottom of the screen I see a list of albums by this artist. Neither left-, right-, or double-clicking does anything other than selecting the album in that specific screen. I would expect to be able to play, or "open" the album from there. 
![Screenshot from 2019-11-06 11-37-24](https://user-images.githubusercontent.com/35520461/68291306-d9a1ca80-0089-11ea-8195-46cc8bcd3207.png)

**Comment by alainm23** [comment]
Thank you very much for your comments. This feature is not yet implemented so it is not a bug. However it is in the plans.

**Comment by Roelofpieter** [comment]
Ah, great! Then I don't need to look further. Thanks very much!
