### ISSUE TITLE
Byte change size by its own.

### ISSUE THREAD

**Issue by themispetras** [alainm23/byte#55]
ΗΙ,
I really love this application. I use it every day for many hours and it has exactly the functions I want. Unfortunately, a bug occurred after the last upgrade. Every time I close and open the byte it  changes the size of the window by its own. It gets bigger and forgets the boundaries I've set. It's really annoying.

**Comment by alainm23** [comment]
This is very strange, I try to reproduce the bug but I can't.
- Did you download Byte from AppCenter or Flathub? 
- Is it possible that you can send me a screenshot of the Byte values ​​in dconf?
- Could you reset the Byte values ​​in dconf?

![image](https://user-images.githubusercontent.com/33765137/69680088-d9d52a80-1077-11ea-8993-5397f83abb14.png)

**Comment by themispetras** [comment]
I downloaded it from Appcender a few months ago and it was working properly. The error started a few days ago. I uninstalled it and reinstalled trying to fix the problem but it was not.
In what folder is the dconf stored?
I looked at  home / .config / dconf folder and found an encoded file called user.

**Comment by alainm23** [comment]
You need to install dconf.

Try to install `sudo apt install elementary-sdk`

**Comment by themispetras** [comment]
![Screenshot from 2019-11-27 01 55 11](https://user-images.githubusercontent.com/58137773/69682107-078e9380-10b9-11ea-97b5-d1f9e539698e.jpeg)

**Comment by themispetras** [comment]
As you can see in this screenshot after reopened, the current value changes due to custom value. 
![Screenshot from 2019-11-27 02 15 26](https://user-images.githubusercontent.com/58137773/69683010-ff842300-10bb-11ea-9647-a26b89bc381e.jpeg)

**Comment by alainm23** [comment]
Can you build byte from this repository, I made some changes to fix this error.

```
git clone https://github.com/alainm23/byte.git
cd byte
meson build && cd build
meson configure -Dprefix=/usr
sudo ninja install
com.github.alainm23.byte
```

**Comment by themispetras** [comment]
I did it but the problem is the same again. Thank you very much for your help but there is no reason to try any more. I resize it every time i launch it so this is not such a big deal. I can handle it. Thank you!
