### ISSUE TITLE
The Brazilian Portuguese is not completely done

### ISSUE THREAD

**Issue by gleissonjoaquim3** [alainm23/byte#69]
The translation into Brazilian Portuguese is not completely done (image below). I installed the program for the first time which is excellent, but it could have this improvement in the translation into my language.
I can help with this translation...
![Captura de tela de 2020-01-28 12 11 07](https://user-images.githubusercontent.com/55757359/73276348-4dee9480-41c7-11ea-9d17-754583dc7900.png)

**Comment by NathanBnm** [comment]
The `pt_BR` translations file does not exist here https://github.com/alainm23/byte/tree/master/po. That's why your translation does not show.
You can freely open a PR to add them.
@alainm23 would be great to add some documentation about that. Maybe a README in the po directory to help translators.

**Comment by gleissonjoaquim3** [comment]
> The `pt_BR` translations file does not exist here https://github.com/alainm23/byte/tree/master/po. That's why your translation does not show.
> You can freely open a PR to add them.
> @alainm23 would be great to add some documentation about that. Maybe a README in the po directory to help translators.

Ok ! I'll do !!
