### ISSUE TITLE
Customizable header and color theme

### ISSUE THREAD

**Issue by Fatih20** [alainm23/byte#8]
In Planner, also an app by @alainm23. We have multiple color style that will change the color of the headerbar and many other elements of the apps UI. I think we should have that too in this app.

**Comment by alainm23** [comment]
The truth is that the color red already got tired, soon an update.

![theme 01](https://user-images.githubusercontent.com/33765137/64221914-17208680-ce94-11e9-8f20-64cdaa0eb338.png)
![theme 2](https://user-images.githubusercontent.com/33765137/64221917-1982e080-ce94-11e9-985e-6ed71f3c2536.png)
