### ISSUE TITLE
Tittle and Description desapear when I click on a radio

### ISSUE THREAD

**Issue by aimproxy** [alainm23/byte#9]
HI, I don't know if you seen this, but when you to to add a new radio, you search one, and if you click in the title it's just despairing, it's not should be selected by the away?

![Screenshot from 2019-08-07 19 12 54](https://user-images.githubusercontent.com/47716563/62646974-692ec480-b947-11e9-8f75-712076dc72f6.png)

**Comment by alainm23** [comment]
It's awkward on my part, I corrected it shortly
