### ISSUE TITLE
Black background

### ISSUE THREAD

**Issue by Sacha-Ringenbach** [alainm23/byte#94]
Hello, I am running into this issue with the player. My compositor is Picom, but I tried with XcompMGR aswell.

I have tried multiple configs but can't seem to correct this background, any insight ?

![image](https://user-images.githubusercontent.com/33430712/98483749-f6ab3500-21d8-11eb-86ae-7218a9b93f21.png)

**Comment by hanaral** [comment]
This is a side effect of the elementary stylesheet using Gtk's native shadow drawing, which a lot of minimal compositors don't support.
